In [18]:
# data types and event attencance/ tabling attendance then ready for join and report prep


#...issues with fab and staff emails

In [19]:
# this is boiler plate for when we move stuff into SQL. I think it will need to be cleaned before SQL. 

import pandas as pd
import pyodbc
import time
import numpy as np
from datetime import datetime, date, time, timedelta

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns',None)

In [20]:

asanaData_raw = pd.read_csv('2025_events_Planning.csv')

In [21]:
#????????what do I do about tabling location and event location....need to combine them

columns_to_rename = {

       'Due Date': 'Date', 
       'Set Up Time ( 00:00 am/pm)':"Set Up Time",
    'Start Time ( 00:00 am/pm)':"Start Time",
       'End Time ( 00:00 am/pm)':"End Time",
    'Location':'Event Location',
       'Event Zip Code':"Zip", 
       'Reason for Not Attending':"Reason for NA",
       'How many staff attended?':"# Staff Attended",
    'How many FAB members attended?':"# FAB Attended",
       'How many interns attended?':"# Interns Attended",
    'How many volunteers attended?':"# Volunteers Attended",
       'How many people attended this event?':"# of People at Event",
       'How did you get the total public attendance number?':"Method of # P@E"
}

In [22]:
asanaData_raw.rename(columns=columns_to_rename,inplace = True)

In [23]:
for i in range(len(asanaData_raw)):
    if asanaData_raw.loc[i, 'Category'] == 'Community Event':
        asanaData_raw.loc[i, 'Location'] = asanaData_raw.loc[i, "Event Location"]

    elif asanaData_raw.loc[i, 'Category'] == 'Partner Tabling':
        asanaData_raw.loc[i, 'Location'] = asanaData_raw.loc[i, 'Tabling Location']
 
    else:
        asanaData_raw.loc[i, 'Category'] = 'error'
        print(f"Row {i}: Unexpected value in 'Category': {asanaData_raw.loc[i, 'Category']}")

Row 0: Unexpected value in 'Category': error
Row 1: Unexpected value in 'Category': error
Row 111: Unexpected value in 'Category': error

In [24]:
asanaData_raw.to_csv('DeletME.csv')

In [25]:
asanaData_raw['Date'] = pd.to_datetime(asanaData_raw['Date'], errors='coerce').dt.date

In [26]:
# to get the names of the columns that need to be renamed
asanaData_raw.columns

Index(['Task ID', 'Created At', 'Completed At', 'Last Modified', 'Name',
       'Section/Column', 'Assignee', 'Assignee Email', 'Start Date', 'Date',
       'Tags', 'Notes', 'Projects', 'Parent task', 'Blocked By (Dependencies)',
       'Blocking (Dependencies)', 'Event Status', 'Category',
       'Est. # of Staff NEEDED', 'Staff Attending', '# of Possible FAB',
       'FAB Attending', 'Open to Interns', 'Intern(s) Attending',
       'Volunteers Needed', 'Volunteers Attending', 'Set Up Time',
       'Start Time', 'End Time', 'Event Location', 'Tabling Location',
       'Address', 'Zip', 'PN?', 'Special Notes', 'Social Media', 'City',
       'KDL Branch', 'GRPL Branch', 'Assignee Attendance', 'Reason for NA',
       'Est. Attendance', '# Staff Attended', '# FAB Attended',
       '# Interns Attended', '# Volunteers Attended', 'Method of # P@E',
       'Host(s)', 'Location'],
      dtype='object')

In [27]:
Coumns_to_Remove = {     'Created At',
                         'Completed At', 'Last Modified', 
                         'Section/Column',
                         'Assignee Email',
                         'Start Date',
                         'Tags',
                         'Notes', 
                         'Blocked By (Dependencies)',
                         'Blocking (Dependencies)',
                         'Est. # of Staff NEEDED', 
                         '# of Possible FAB',
                         'Open to Interns',
                         'Volunteers Needed', 
                         'Special Notes',
                         'Assignee Attendance','Event Location', 'Tabling Location',
       }

asanaData_raw.drop(Coumns_to_Remove,inplace = True, axis = 1)

In [28]:
asanaData_raw = asanaData_raw.drop(index=0)

In [29]:
# making a function to bulk force ID---> string and dates into best tableau format

# ---variables ---
df = asanaData_raw

id_column = 'Task ID'

date_columns = ['Date', 
    
]

# --- function ---
def format_columns(df, id_column, date_columns):
    df = df.copy()  

    # Convert ID column to string
    df[id_column] = df[id_column].astype(str)

    # Convert and format each date column
    for col in date_columns:
        df[col] = pd.to_datetime(df[col], errors='coerce')
        df[col] = df[col].dt.strftime('%m-%d-%Y')

    return df

# --- Run the function ---
df = format_columns(df, id_column, date_columns)
asanaData_raw = df

In [30]:
#creating an Event Id so that when I join on the survey data I can still sort by Occurance, some tablings have the same name every time
asanaData_raw['Event ID'] = ['E' + str(i + 1) for i in range(len(asanaData_raw))]
asanaData_raw['Event ID'] = asanaData_raw['Event ID'].astype(str)

In [31]:
asanaData_raw.to_csv('Local_asanaData.csv',index = False)    # this if for joining on SurveyMonkey




Columns_to_Remove2 = {   'Staff Attending',
 'FAB Attending',
 'Intern(s) Attending',
 'Volunteers Attending'
       }

asanaData_raw_single = asanaData_raw.drop(Columns_to_Remove2, axis = 1)


asanaData_raw_single.to_csv('Local_asanaData_single.csv',index = False) # this is for staffing counts in tableau

In [32]:

#making a table of dates for the events to correct for large multi day events like pride
include_keywords = ['Grand Rapids Pride','SHOES Program']

asana_dates = asanaData_raw[
    #taking out tablings
    (asanaData_raw['Category'] == 'Community Event') &
    # taking out historical data where there will not be any survey data to join on
    (pd.to_datetime(asanaData_raw['Date']) > pd.to_datetime('2025-06-01')) &
    # taking out a few communtiy events that have multiples
    (asanaData_raw['Name'].str.strip().isin(include_keywords))
][['Name', 'Date']].copy()

asana_dates['Name'].unique()
#asana_dates.head(20)
asana_dates.to_csv('asana_dates_clean.csv', index=False)

In [33]:
asana_dates.head(260)
#asana_dates['Name'].unique()

# See any rows containing the problematic phrases
#mask = asanaData_raw['Name'].str.lower().str.contains('lincoln park|community night', na=False)
#print(asanaData_raw[mask][['Name']])

                   Name        Date
48        SHOES Program  08-15-2025
106  Grand Rapids Pride  06-22-2025

In [34]:
asanaData_raw.head(3)

,Task ID,Name,Assignee,Date,Projects,Parent task,Event Status,Category,Staff Attending,FAB Attending,Intern(s) Attending,Volunteers Attending,Set Up Time,Start Time,End Time,Address,Zip,PN?,Social Media,City,KDL Branch,GRPL Branch,Reason for NA,Est. Attendance,# Staff Attended,# FAB Attended,# Interns Attended,# Volunteers Attended,Method of # P@E,Host(s),Location,Event ID
1,1210114866889281,Add an Event or Tabling! (Link in description),NaN,NaN,2025 Events Planning,NaN,NaN,error,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,E1
2,1211166238157232,Children's Workshop's Family Fun Night,Christina Pocklington,09-30-2025,2025 Events Planning,NaN,Pending Decision,Community Event,NaN,NaN,NaN,NaN,5:00 PM,5:30 PM,7:00 PM,"2727 Michigan St NE, Grand Rapids, MI 49506",49506.0,No,No,Grand Rapids,NaN,NaN,NaN,100.0,NaN,NaN,NaN,NaN,NaN,Children's Workshop,Children's Workshop--outside,E2
3,1210535068706211,Trunk or Treat for Lead Defeat,Lianna Tagle,10-23-2025,"Community Events Calendar,2025 Events Planning",NaN,Pending Decision,Community Event,NaN,NaN,NaN,NaN,TBD,5 pm,7 pm,1545 Buchanan Ave SW,49507.0,No,Yes,Grand Rapids,NaN,NaN,NaN,500.0,NaN,NaN,NaN,NaN,NaN,Healthy Homes Coalition,SECOM/Healthy Homes parking lot,E3

In [35]:
# add a numberical line for data eval? just an idea